# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20170410_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
