# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_profile_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='street',
            new_name='street_name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
